package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import model.cliente;
import controlador.correoSoporte;
import controlador.crud_planes;
import controlador.ctrlFactura;
import model.Planes;
import static entidades.Arreglos.*;
import java.time.LocalDate;
import model.factura;

/**
 *
 * @author Juanes
 */

public class usuarioVista extends javax.swing.JFrame {
   
   
    private cliente usuarioActual;
    
    
    
    public usuarioVista(){
        initComponents();
        this.setLocationRelativeTo(this);
}

    public void setUsuarioActual(cliente usuarioActual) {
        this.usuarioActual = usuarioActual;
    }

    private Planes obtenerPlanDelUsuario() {
        if (usuarioActual == null) {
            return null;
        }

        Planes planAsignado = crud_planes.buscarPlanPorNombre(usuarioActual.getPlanActual());
        if (planAsignado != null) {
            return planAsignado;
        }

        return crud_planes.obtenerPrimerPlanDisponible();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        JpnMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelInicio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JpnCerrarSesion = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jPanelMiplan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanelMisDatos = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        JpnSoporte = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        JpnPng = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        JpnBienvenida = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        JpnMiplan = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnFacturacion = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        btnDetalles = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnCambioplan = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        JpnMisDatos = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        cbTipoDocumento = new javax.swing.JComboBox<>();
        txtIdentificacion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txPassword = new javax.swing.JPasswordField();
        btnActualizarInfo = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnvolver1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jpnSoporte = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnEnviarSoporte = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtAsunto = new javax.swing.JTextField();
        btnVolver2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        JpnDetalles = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtnombrePlan = new javax.swing.JTextField();
        txtmetodoPago = new javax.swing.JTextField();
        txtvalorMensual = new javax.swing.JTextField();
        txtfechaVencimiento = new javax.swing.JTextField();
        txtfechaActivacion = new javax.swing.JTextField();
        txtestado = new javax.swing.JTextField();
        txtDescripcionPlan = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtIdPlan = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        btnvolver3 = new javax.swing.JButton();
        JpnFacturacion = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cbMes = new javax.swing.JComboBox<>();
        cbAno = new javax.swing.JComboBox<>();
        btnVerFactura = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        btnvolver4 = new javax.swing.JButton();
        JpnActualizarDatos = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        txtActualizarNombres = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        txtActApellidos = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        txtActDireccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        txtActTelefono = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        txtActCorreo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNuevaContraseña = new javax.swing.JPasswordField();
        txtContraseñaActual = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JpnMenu.setBackground(new java.awt.Color(255, 204, 102));
        JpnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/gente.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        JpnMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 29, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");
        JpnMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 99, -1, -1));

        jPanelInicio.setBackground(new java.awt.Color(255, 204, 102));
        jPanelInicio.setForeground(new java.awt.Color(255, 255, 255));
        jPanelInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelInicioMouseExited(evt);
            }
        });
        jPanelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INICIO");
        jPanelInicio.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, 160, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/icons8-home-28.png"))); // NOI18N
        jPanelInicio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        JpnMenu.add(jPanelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 158, -1, 36));

        JpnCerrarSesion.setBackground(new java.awt.Color(255, 204, 102));
        JpnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpnCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JpnCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JpnCerrarSesionMouseExited(evt);
            }
        });
        JpnCerrarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/icons8-logout-28.png"))); // NOI18N
        JpnCerrarSesion.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Cerrar Sesion");
        JpnCerrarSesion.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 160, 50));

        JpnMenu.add(JpnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 447, 200, 50));

        jPanelMiplan.setBackground(new java.awt.Color(255, 204, 102));
        jPanelMiplan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMiplanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMiplanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMiplanMouseExited(evt);
            }
        });
        jPanelMiplan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MI PLAN");
        jPanelMiplan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, 160, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/icons8-list-28 (1).png"))); // NOI18N
        jPanelMiplan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        JpnMenu.add(jPanelMiplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, 40));

        jPanelMisDatos.setBackground(new java.awt.Color(255, 204, 102));
        jPanelMisDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMisDatosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMisDatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMisDatosMouseExited(evt);
            }
        });
        jPanelMisDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("MIS DATOS");
        jPanelMisDatos.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, 160, 28));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/icons8-male-user-28.png"))); // NOI18N
        jPanelMisDatos.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        JpnMenu.add(jPanelMisDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 246, 200, 40));

        JpnSoporte.setBackground(new java.awt.Color(255, 204, 102));
        JpnSoporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpnSoporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JpnSoporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JpnSoporteMouseExited(evt);
            }
        });
        JpnSoporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SOPORTE");
        JpnSoporte.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, 160, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/icons8-support-28.png"))); // NOI18N
        JpnSoporte.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        JpnMenu.add(JpnSoporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 292, -1, -1));

        getContentPane().add(JpnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 500));

        JpnPng.setBackground(new java.awt.Color(137, 207, 240));
        JpnPng.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("WiNet Control");
        JpnPng.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, 250, 50));

        getContentPane().add(JpnPng, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 780, 110));

        JpnBienvenida.setBackground(new java.awt.Color(255, 255, 255));
        JpnBienvenida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel15.setText("Bienvenido, usuario!");
        JpnBienvenida.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/icons8-waving-hand-medium-skin-tone-48.png"))); // NOI18N
        JpnBienvenida.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel61.setText("Recuerda que en WiNet Control estamos para servirte...");
        jLabel61.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        JpnBienvenida.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 380, 20));

        jTabbedPane1.addTab("0", JpnBienvenida);

        JpnMiplan.setBackground(new java.awt.Color(255, 255, 255));
        JpnMiplan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("MI PLAN");
        JpnMiplan.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        btnFacturacion.setBackground(new java.awt.Color(137, 207, 240));
        btnFacturacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFacturacion.setForeground(new java.awt.Color(255, 255, 255));
        btnFacturacion.setText("Mis facturas");
        btnFacturacion.setBorder(null);
        btnFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacionActionPerformed(evt);
            }
        });
        JpnMiplan.add(btnFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 250, 40));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/informacion_1.png"))); // NOI18N
        JpnMiplan.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 40, 40));

        btnDetalles.setBackground(new java.awt.Color(137, 207, 240));
        btnDetalles.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDetalles.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalles.setText("Detalles de mi plan");
        btnDetalles.setBorder(null);
        btnDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesActionPerformed(evt);
            }
        });
        JpnMiplan.add(btnDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 250, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/icons8-invoices-24.png"))); // NOI18N
        JpnMiplan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 40, 40));

        btnCambioplan.setBackground(new java.awt.Color(137, 207, 240));
        btnCambioplan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCambioplan.setForeground(new java.awt.Color(255, 255, 255));
        btnCambioplan.setText("Solicitar cambio plan");
        btnCambioplan.setBorder(null);
        btnCambioplan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambioplanActionPerformed(evt);
            }
        });
        JpnMiplan.add(btnCambioplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 250, 40));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/icons8-update-24.png"))); // NOI18N
        JpnMiplan.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 40, 40));

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/flecha-izquierda.png"))); // NOI18N
        JpnMiplan.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTabbedPane1.addTab("1", JpnMiplan);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setText("Mis datos");
        jPanel17.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        txtDireccion.setFocusable(false);
        jPanel17.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 170, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setText("Numero Telefono");
        jPanel17.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        cbTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", " " }));
        jPanel17.add(cbTipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        txtIdentificacion.setFocusable(false);
        jPanel17.add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 120, -1));

        txtTelefono.setFocusable(false);
        jPanel17.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 130, -1));

        txPassword.setFocusable(false);
        jPanel17.add(txPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 170, 20));

        btnActualizarInfo.setText("Actualizar mis datos");
        btnActualizarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarInfoActionPerformed(evt);
            }
        });
        jPanel17.add(btnActualizarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 160, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel44.setText("Nombres");
        jPanel17.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel45.setText("Apellidos");
        jPanel17.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel46.setText("Documento");
        jPanel17.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel47.setText("Contraseña");
        jPanel17.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel48.setText("Correo Electronico");
        jPanel17.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel49.setText("Dirección");
        jPanel17.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        txtNombres.setFocusable(false);
        jPanel17.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 150, -1));

        txtApellidos.setFocusable(false);
        jPanel17.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 150, -1));

        txtCorreo.setFocusable(false);
        jPanel17.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 130, -1));

        btnvolver1.setText("Volver");
        btnvolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolver1ActionPerformed(evt);
            }
        });
        jPanel17.add(btnvolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 160, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("¿Deseas actualizar tus datos?");
        jPanel17.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Presiona el siguente botón ");
        jPanel17.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 190, -1));

        javax.swing.GroupLayout JpnMisDatosLayout = new javax.swing.GroupLayout(JpnMisDatos);
        JpnMisDatos.setLayout(JpnMisDatosLayout);
        JpnMisDatosLayout.setHorizontalGroup(
            JpnMisDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnMisDatosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JpnMisDatosLayout.setVerticalGroup(
            JpnMisDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnMisDatosLayout.createSequentialGroup()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("2", JpnMisDatos);

        jpnSoporte.setBackground(new java.awt.Color(255, 255, 255));
        jpnSoporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setText("Soporte");
        jpnSoporte.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Asunto:");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Descripcion del problema:");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        btnEnviarSoporte.setBackground(new java.awt.Color(102, 102, 102));
        btnEnviarSoporte.setText("Enviar");
        btnEnviarSoporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarSoporteActionPerformed(evt);
            }
        });
        jPanel7.add(btnEnviarSoporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 80, -1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(null);
        txtDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(txtDescripcion);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 640, -1));
        jPanel7.add(txtAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 630, -1));

        btnVolver2.setText("Volver");
        btnVolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver2ActionPerformed(evt);
            }
        });
        jPanel7.add(btnVolver2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 160, -1));

        jpnSoporte.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 690, 270));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel17.setText("Aqui puedes solicitar el cambio de tu plan, o reportar fallos en el sistema.");
        jpnSoporte.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 510, -1));

        jTabbedPane1.addTab("3", jpnSoporte);

        JpnDetalles.setBackground(new java.awt.Color(255, 255, 255));
        JpnDetalles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Detalles de mi plan");
        JpnDetalles.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("Metodo de pago:");
        JpnDetalles.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setText("ID del plan:");
        JpnDetalles.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setText("Fecha de activacion: ");
        JpnDetalles.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel32.setText("Descripcion del plan:");
        JpnDetalles.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setText("Fecha de vencimiento:");
        JpnDetalles.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel41.setText("Estado del plan:");
        JpnDetalles.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel42.setText("Costo mensual:");
        JpnDetalles.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txtnombrePlan.setFocusable(false);
        JpnDetalles.add(txtnombrePlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 160, -1));

        txtmetodoPago.setFocusable(false);
        JpnDetalles.add(txtmetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 160, -1));

        txtvalorMensual.setFocusable(false);
        JpnDetalles.add(txtvalorMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 160, -1));

        txtfechaVencimiento.setFocusable(false);
        JpnDetalles.add(txtfechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 160, -1));

        txtfechaActivacion.setFocusable(false);
        JpnDetalles.add(txtfechaActivacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 160, -1));

        txtestado.setFocusable(false);
        JpnDetalles.add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 160, -1));

        txtDescripcionPlan.setFocusable(false);
        JpnDetalles.add(txtDescripcionPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 160, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setText("Nombre del plan:");
        JpnDetalles.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtIdPlan.setFocusable(false);
        JpnDetalles.add(txtIdPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 160, -1));

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/flecha-izquierda.png"))); // NOI18N
        JpnDetalles.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnvolver3.setText("Volver");
        btnvolver3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolver3ActionPerformed(evt);
            }
        });
        JpnDetalles.add(btnvolver3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 160, -1));

        jTabbedPane1.addTab("4", JpnDetalles);

        JpnFacturacion.setBackground(new java.awt.Color(255, 255, 255));
        JpnFacturacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Mis facturas");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JpnFacturacion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        cbMes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cbMes.setToolTipText("");
        JpnFacturacion.add(cbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 110, -1));

        cbAno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2026", "2025", "2024" }));
        JpnFacturacion.add(cbAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 110, -1));

        btnVerFactura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerFactura.setText("Ver factura");
        btnVerFactura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerFacturaActionPerformed(evt);
            }
        });
        JpnFacturacion.add(btnVerFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 110, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel38.setText("Recuerda que en WiNet Control estamos para servirte");
        jLabel38.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        JpnFacturacion.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 380, 30));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel39.setText("Bienvenido a la sección facturación!!");
        jLabel39.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        JpnFacturacion.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 400, 30));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel40.setText("Aqui puedes:");
        jLabel40.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        JpnFacturacion.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, 30));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel58.setText("- Consultar tu factura del mes en curso");
        jLabel58.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        JpnFacturacion.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 320, 30));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel59.setText("- El total a pagar");
        jLabel59.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        JpnFacturacion.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 320, 30));

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel60.setText("- Tus servicios contratados");
        jLabel60.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        JpnFacturacion.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 320, 30));

        btnvolver4.setBackground(new java.awt.Color(137, 207, 240));
        btnvolver4.setText("Volver");
        btnvolver4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolver4ActionPerformed(evt);
            }
        });
        JpnFacturacion.add(btnvolver4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 160, -1));

        jTabbedPane1.addTab("5", JpnFacturacion);

        JpnActualizarDatos.setBackground(new java.awt.Color(204, 204, 204));
        JpnActualizarDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel50.setText("Nueva contraseña");
        jPanel6.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 120, -1));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel51.setText("Nombres");
        jPanel6.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, -1));

        txtActualizarNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActualizarNombresActionPerformed(evt);
            }
        });
        jPanel6.add(txtActualizarNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 180, -1));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel52.setText("Apellidos");
        jPanel6.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, -1));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel54.setText("Correo Electronico");
        jPanel6.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 140, -1));
        jPanel6.add(txtActApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 180, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel55.setText("Direccion");
        jPanel6.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 140, -1));
        jPanel6.add(txtActDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 170, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Actualizar mis datos");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel56.setText("Telefono");
        jPanel6.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, -1));
        jPanel6.add(txtActTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 180, -1));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel57.setText("Contraseña actual");
        jPanel6.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 120, -1));
        jPanel6.add(txtActCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 170, -1));

        btnGuardar.setText("Guardar ");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel6.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 90, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel6.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 90, -1));
        jPanel6.add(txtNuevaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 170, -1));
        jPanel6.add(txtContraseñaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 170, -1));

        JpnActualizarDatos.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 370));

        jTabbedPane1.addTab("6", JpnActualizarDatos);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 780, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInicioMouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jPanelInicioMouseClicked

    private void jPanelInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInicioMouseEntered
        jPanelInicio.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_jPanelInicioMouseEntered

    private void jPanelInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInicioMouseExited
        jPanelInicio.setBackground(new Color(255,204,102));
    }//GEN-LAST:event_jPanelInicioMouseExited

    private void jPanelMiplanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMiplanMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jPanelMiplanMouseClicked

    private void jPanelMiplanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMiplanMouseEntered
        jPanelMiplan.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_jPanelMiplanMouseEntered

    private void jPanelMiplanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMiplanMouseExited
        jPanelMiplan.setBackground(new Color(255,204,102));
    }//GEN-LAST:event_jPanelMiplanMouseExited

    private void jPanelMisDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMisDatosMouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jPanelMisDatosMouseClicked

    private void jPanelMisDatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMisDatosMouseEntered
        jPanelMisDatos.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_jPanelMisDatosMouseEntered

    private void jPanelMisDatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMisDatosMouseExited
        jPanelMisDatos.setBackground(new Color(255,204,102));
    }//GEN-LAST:event_jPanelMisDatosMouseExited

    private void JpnSoporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpnSoporteMouseClicked
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_JpnSoporteMouseClicked

    private void JpnSoporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpnSoporteMouseEntered
        JpnSoporte.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_JpnSoporteMouseEntered

    private void JpnSoporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpnSoporteMouseExited
        JpnSoporte.setBackground(new Color(255,204,102));
    }//GEN-LAST:event_JpnSoporteMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void JpnCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpnCerrarSesionMouseEntered
        JpnCerrarSesion.setBackground(new Color (204,204,204));
    }//GEN-LAST:event_JpnCerrarSesionMouseEntered

    private void JpnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpnCerrarSesionMouseExited
        JpnCerrarSesion.setBackground(new Color (255,204,102));
    }//GEN-LAST:event_JpnCerrarSesionMouseExited

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombre= txtActualizarNombres.getText().trim();
        String apellidos= txtActApellidos.getText().trim();
        String telefono= txtActTelefono.getText().trim();
        String direccion= txtActDireccion.getText().trim();
        String correo= txtActCorreo.getText().trim();
        String contrasenaactual= new String (txtContraseñaActual.getPassword());
        String contrasenanueva = new String(txtNuevaContraseña.getPassword());

        if (nombre.isEmpty()) {
            
        }
        
        if(!telefono.matches("\\d{10}")){
            JOptionPane.showMessageDialog(this,"El numero de telefono debe tener exactamente 10 numeros");
            return;

        }

        if(!correo.endsWith("@gmail.com")){
            JOptionPane.showMessageDialog(this, "Correo invalido");
            return;
        }

        if(contrasenaactual.equals(contrasenanueva)){
            JOptionPane.showMessageDialog(this, "La nueva contraseña debe ser distinta");
            return;
        }

        if(contrasenanueva.length() < 8){
            JOptionPane.showMessageDialog(this, "La contrasena debe contener minimo 8 caracteres");
            return;

        }

        JOptionPane.showMessageDialog(this, "Datos actualizados correctamente");

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtActualizarNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActualizarNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActualizarNombresActionPerformed

    private void btnEnviarSoporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarSoporteActionPerformed
     String usuario = usuarioActual.getNombre() + " " + usuarioActual.getApellido(); // tu objeto Usuario
    String asunto = txtAsunto.getText();
    String mensaje = txtDescripcion.getText();

    if(asunto.isEmpty() || mensaje.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Completa todos los campos");
        return;
    }

    String mensajeCompleto = "Usuario: " + usuario + "\n\n" + mensaje;

    boolean enviado = correoSoporte.enviarCorreo("mauriciomaldonadomercado@gmail.com", asunto, mensajeCompleto);

    if(enviado) {
        JOptionPane.showMessageDialog(this, "Mensaje enviado correctamente");
        txtAsunto.setText("");
        txtDescripcion.setText("");
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo enviar el mensaje");
    }
    }//GEN-LAST:event_btnEnviarSoporteActionPerformed

    private void btnActualizarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarInfoActionPerformed
        jTabbedPane1.setSelectedIndex(6);
       
    }//GEN-LAST:event_btnActualizarInfoActionPerformed

    private void btnCambioplanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambioplanActionPerformed
       jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnCambioplanActionPerformed

    private void btnDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesActionPerformed
        jTabbedPane1.setSelectedIndex(4);
        
        Planes planActual = obtenerPlanDelUsuario();
        if (planActual != null) {
        txtIdPlan.setText(String.valueOf(planActual.getIdPlan()));
        txtnombrePlan.setText(planActual.getNombrePlan());
        txtvalorMensual.setText(String.valueOf(planActual.getPrecio()));
        txtDescripcionPlan.setText(planActual.getDescripcionPlan());
        txtfechaActivacion.setText(planActual.getFechaActivacion());
  
        
        txtIdPlan.setEditable(false);
        txtnombrePlan.setEditable(false);
        txtvalorMensual.setEditable(false);
        txtDescripcionPlan.setEditable(false);
        txtfechaVencimiento.setEditable(false);
        txtfechaActivacion.setEditable(false);
        txtestado.setEditable(false);
        txtmetodoPago.setEditable(false);
    } else {
        JOptionPane.showMessageDialog(this, "El usuario no tiene un plan asignado.");
    }
        
    }//GEN-LAST:event_btnDetallesActionPerformed

    private void btnFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionActionPerformed
        jTabbedPane1.setSelectedIndex(5);
        
    cliente usuario = usuarioActual;  
    if (usuario == null) {
        JOptionPane.showMessageDialog(this, "No hay usuario logueado.");
        return;
    }

    // busca la factura del mes actual
    java.time.LocalDate hoy = java.time.LocalDate.now();
    int mes = hoy.getMonthValue();
    int ano = hoy.getYear();

    model.factura f = controlador.ctrlFactura.buscarFacturaMes(usuario.getNombre()+ "" + usuario.getApellido(), mes, ano);
    if (f == null) {
        JOptionPane.showMessageDialog(this, "No tienes facturas en este mes.");
        return;
    }

    // abre el PDF directamente
    try {
        java.awt.Desktop.getDesktop().open(new java.io.File(f.getArchivoPDF()));
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al abrir el PDF: " + e.getMessage());
    }

    }//GEN-LAST:event_btnFacturacionActionPerformed

    private void btnVerFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerFacturaActionPerformed
  
    String nombreCompleto = usuarioActual.getNombre() + " " + usuarioActual.getApellido();

    Planes planUsuario = obtenerPlanDelUsuario();
    if (planUsuario == null) {
        JOptionPane.showMessageDialog(this, "No hay planes disponibles para generar factura.");
        return;
    }

    int mesSeleccionado = cbMes.getSelectedIndex() + 1;
    int anoSeleccionado = Integer.parseInt((String) cbAno.getSelectedItem());

    LocalDate hoy = LocalDate.now();
    int mesActual = hoy.getMonthValue();
    int anoActual = hoy.getYear();

    if (mesSeleccionado != mesActual || anoSeleccionado != anoActual) {
        JOptionPane.showMessageDialog(this, "No se generaron facturas para meses anteriores.");
        return;
    }

    String archivoPDF = "facturas/factura_" + nombreCompleto.replace(" ", "_") + "-" + mesActual + "-" + anoActual + ".pdf";

    factura f = ctrlFactura.buscarFacturaMes(nombreCompleto, mesActual, anoActual);

    if (f == null) {
        f = ctrlFactura.crearFactura(nombreCompleto, planUsuario, archivoPDF);
        ctrlFactura.generarFacturaPDF(f, planUsuario);
    }

    try {
        java.awt.Desktop.getDesktop().open(new java.io.File(f.getArchivoPDF()));
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al abrir la factura: " + e.getMessage());
    }

        
    }//GEN-LAST:event_btnVerFacturaActionPerformed

    private void JpnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpnCerrarSesionMouseClicked
        login Login = new login();
        Login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JpnCerrarSesionMouseClicked

    private void btnvolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolver1ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnvolver1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver2ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnVolver2ActionPerformed

    private void btnvolver3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolver3ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnvolver3ActionPerformed

    private void btnvolver4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolver4ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnvolver4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
        usuarioVista usu = new usuarioVista();
        usu.setVisible(true);
        
    };
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpnActualizarDatos;
    private javax.swing.JPanel JpnBienvenida;
    private javax.swing.JPanel JpnCerrarSesion;
    private javax.swing.JPanel JpnDetalles;
    private javax.swing.JPanel JpnFacturacion;
    private javax.swing.JPanel JpnMenu;
    private javax.swing.JPanel JpnMiplan;
    private javax.swing.JPanel JpnMisDatos;
    private javax.swing.JPanel JpnPng;
    private javax.swing.JPanel JpnSoporte;
    private javax.swing.JButton btnActualizarInfo;
    private javax.swing.JButton btnCambioplan;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDetalles;
    private javax.swing.JButton btnEnviarSoporte;
    private javax.swing.JButton btnFacturacion;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVerFactura;
    private javax.swing.JButton btnVolver2;
    private javax.swing.JButton btnvolver1;
    private javax.swing.JButton btnvolver3;
    private javax.swing.JButton btnvolver4;
    private javax.swing.JComboBox<String> cbAno;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JComboBox<String> cbTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JPanel jPanelMiplan;
    private javax.swing.JPanel jPanelMisDatos;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jpnSoporte;
    private javax.swing.JPasswordField txPassword;
    private javax.swing.JTextField txtActApellidos;
    private javax.swing.JTextField txtActCorreo;
    private javax.swing.JTextField txtActDireccion;
    private javax.swing.JTextField txtActTelefono;
    private javax.swing.JTextField txtActualizarNombres;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtAsunto;
    private javax.swing.JPasswordField txtContraseñaActual;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtDescripcionPlan;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdPlan;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JPasswordField txtNuevaContraseña;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtfechaActivacion;
    private javax.swing.JTextField txtfechaVencimiento;
    private javax.swing.JTextField txtmetodoPago;
    private javax.swing.JTextField txtnombrePlan;
    private javax.swing.JTextField txtvalorMensual;
    // End of variables declaration//GEN-END:variables

}
