package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import model.soporte;
import model.Usuario;
import model.plan;
import controlador.correoSoporte;
import controlador.Crud_Planes;
public class usuario extends javax.swing.JFrame {
   
    private plan planActual;
    private Usuario usuarioActual;
    private soporte soporte;
    
    
    
    public usuario(Usuario usuario){
        initComponents();
        this.usuarioActual = usuario;
        
        txtNombres.setText(usuario.getNombre());
        txtTelefono.setText(usuario.getNombre());
        txtApellidos.setText(usuario.getApellido());
        txtTelefono.setText(usuario.getTelefono());
        txtCorreo.setText(usuario.getCorreo());
        cbTipoDocumento.setSelectedItem(usuario.getTipoDocumento());
        txtIdentificacion.setText(usuario.getIdentificacion());
        txtDireccion.setText(usuario.getDireccion());
        txPassword.setText(usuario.getContrasena());
        
        txtTelefono.setEditable(false);
        txtApellidos.setEditable(false);
        txtTelefono.setEditable(false);
        txtDireccion.setEditable(false);
        cbTipoDocumento.setEditable(false);
        txtIdentificacion.setEditable(false);
        txtDireccion.setEditable(false);
        txPassword.setEditable(false);
        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        JpnMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelInicio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JpnCerrarSesion = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanelMiplan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanelMisDatos = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        JpnSoporte = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        JpnPng = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        JpnBienvenida = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        JpnMiplan = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnFacturacion = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnOpciones = new javax.swing.JButton();
        btnDetalles = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnActualizarPlan = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        btnOpciones1 = new javax.swing.JButton();
        JpnMisDatos = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        cbTipoDocumento = new javax.swing.JComboBox<>();
        txtIdentificacion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txPassword = new javax.swing.JPasswordField();
        btnActualizarInfo = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jpnSoporte = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnEnviarSoporte = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtAsunto = new javax.swing.JTextField();
        JpnDetalles = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtnombrePlan = new javax.swing.JTextField();
        txtmetodoPago = new javax.swing.JTextField();
        txtvalorMensual = new javax.swing.JTextField();
        txtfechaVencimiento = new javax.swing.JTextField();
        txtfechaActivacion = new javax.swing.JTextField();
        txtestado = new javax.swing.JTextField();
        txtDescripcionPlan = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtIdPlan = new javax.swing.JTextField();
        JpnFacturacion = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        JpnCambiarPlan = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        JpnActualizarDatos = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        txtActualizarNombres = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        txtActApellidos = new javax.swing.JTextField();
        txtActNoDocumento = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        txtActDireccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        txtActTelefono = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        txtActCorreo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNuevaContraseña = new javax.swing.JPasswordField();
        txtContraseñaActual = new javax.swing.JPasswordField();
        JpnActualizarMetodoPago = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JpnMenu.setBackground(new java.awt.Color(59, 130, 246));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/gente.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");

        jPanelInicio.setBackground(new java.awt.Color(59, 130, 246));
        jPanelInicio.setForeground(new java.awt.Color(255, 255, 255));
        jPanelInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelInicioMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INICIO");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/icons8-home-28.png"))); // NOI18N

        javax.swing.GroupLayout jPanelInicioLayout = new javax.swing.GroupLayout(jPanelInicio);
        jPanelInicio.setLayout(jPanelInicioLayout);
        jPanelInicioLayout.setHorizontalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanelInicioLayout.setVerticalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(135, 135, 135))
        );

        JpnCerrarSesion.setBackground(new java.awt.Color(59, 130, 246));
        JpnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JpnCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JpnCerrarSesionMouseExited(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Cerrar Sesion");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/icons8-logout-28.png"))); // NOI18N

        javax.swing.GroupLayout JpnCerrarSesionLayout = new javax.swing.GroupLayout(JpnCerrarSesion);
        JpnCerrarSesion.setLayout(JpnCerrarSesionLayout);
        JpnCerrarSesionLayout.setHorizontalGroup(
            JpnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnCerrarSesionLayout.createSequentialGroup()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpnCerrarSesionLayout.setVerticalGroup(
            JpnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnCerrarSesionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JpnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27))
                .addContainerGap())
        );

        jPanelMiplan.setBackground(new java.awt.Color(59, 130, 246));
        jPanelMiplan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMiplanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMiplanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMiplanMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MI PLAN");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/icons8-list-28 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanelMiplanLayout = new javax.swing.GroupLayout(jPanelMiplan);
        jPanelMiplan.setLayout(jPanelMiplanLayout);
        jPanelMiplanLayout.setHorizontalGroup(
            jPanelMiplanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMiplanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanelMiplanLayout.setVerticalGroup(
            jPanelMiplanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMiplanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMiplanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(92, 92, 92))
        );

        jPanelMisDatos.setBackground(new java.awt.Color(59, 130, 246));
        jPanelMisDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMisDatosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMisDatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMisDatosMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("MIS DATOS");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/icons8-male-user-28.png"))); // NOI18N

        javax.swing.GroupLayout jPanelMisDatosLayout = new javax.swing.GroupLayout(jPanelMisDatos);
        jPanelMisDatos.setLayout(jPanelMisDatosLayout);
        jPanelMisDatosLayout.setHorizontalGroup(
            jPanelMisDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMisDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMisDatosLayout.setVerticalGroup(
            jPanelMisDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMisDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMisDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );

        JpnSoporte.setBackground(new java.awt.Color(59, 130, 246));
        JpnSoporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpnSoporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JpnSoporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JpnSoporteMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SOPORTE");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/icons8-support-28.png"))); // NOI18N

        javax.swing.GroupLayout JpnSoporteLayout = new javax.swing.GroupLayout(JpnSoporte);
        JpnSoporte.setLayout(JpnSoporteLayout);
        JpnSoporteLayout.setHorizontalGroup(
            JpnSoporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnSoporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpnSoporteLayout.setVerticalGroup(
            JpnSoporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnSoporteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpnSoporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JpnMenuLayout = new javax.swing.GroupLayout(JpnMenu);
        JpnMenu.setLayout(JpnMenuLayout);
        JpnMenuLayout.setHorizontalGroup(
            JpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMiplan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JpnMenuLayout.createSequentialGroup()
                .addGroup(JpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpnMenuLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1))
                    .addGroup(JpnMenuLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addComponent(JpnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JpnSoporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMisDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JpnMenuLayout.setVerticalGroup(
            JpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnMenuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jPanelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMiplan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMisDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpnSoporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(JpnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        getContentPane().add(JpnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 520));

        JpnPng.setBackground(new java.awt.Color(255, 255, 255));
        JpnPng.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("WiNet Control");
        JpnPng.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/ChatGPT Image 22 oct 2025, 08_12_24 p.m..png"))); // NOI18N
        JpnPng.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 110));

        getContentPane().add(JpnPng, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 780, 100));

        JpnBienvenida.setBackground(new java.awt.Color(204, 204, 204));
        JpnBienvenida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Bienvenido, usuario!");
        JpnBienvenida.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/icons8-waving-hand-medium-skin-tone-48.png"))); // NOI18N
        JpnBienvenida.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jTabbedPane1.addTab("0", JpnBienvenida);

        JpnMiplan.setBackground(new java.awt.Color(204, 204, 204));
        JpnMiplan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("MI PLAN");
        JpnMiplan.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        btnFacturacion.setBackground(new java.awt.Color(59, 130, 246));
        btnFacturacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFacturacion.setForeground(new java.awt.Color(255, 255, 255));
        btnFacturacion.setText("Mis facturas");
        btnFacturacion.setBorder(null);
        btnFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacionActionPerformed(evt);
            }
        });
        JpnMiplan.add(btnFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 200, 40));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/icons8-info-24.png"))); // NOI18N
        JpnMiplan.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 40, 40));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/icons8-update-24.png"))); // NOI18N
        JpnMiplan.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 50, 40));

        btnOpciones.setBackground(new java.awt.Color(59, 130, 246));
        btnOpciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnOpciones.setForeground(new java.awt.Color(255, 255, 255));
        btnOpciones.setText("Eliminar cuenta");
        btnOpciones.setBorder(null);
        btnOpciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionesActionPerformed(evt);
            }
        });
        JpnMiplan.add(btnOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 250, 40));

        btnDetalles.setBackground(new java.awt.Color(59, 130, 246));
        btnDetalles.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDetalles.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalles.setText("Detalles de mi plan");
        btnDetalles.setBorder(null);
        btnDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesActionPerformed(evt);
            }
        });
        JpnMiplan.add(btnDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 200, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/icons8-invoices-24.png"))); // NOI18N
        JpnMiplan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 50, 40));

        btnActualizarPlan.setBackground(new java.awt.Color(59, 130, 246));
        btnActualizarPlan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnActualizarPlan.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarPlan.setText(" Actualizar plan");
        btnActualizarPlan.setBorder(null);
        btnActualizarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPlanActionPerformed(evt);
            }
        });
        JpnMiplan.add(btnActualizarPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 200, 40));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/icons8-update-24.png"))); // NOI18N
        JpnMiplan.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 50, 40));

        btnOpciones1.setBackground(new java.awt.Color(59, 130, 246));
        btnOpciones1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnOpciones1.setForeground(new java.awt.Color(255, 255, 255));
        btnOpciones1.setText("Actualizar metodo de pago");
        btnOpciones1.setBorder(null);
        btnOpciones1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOpciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpciones1ActionPerformed(evt);
            }
        });
        JpnMiplan.add(btnOpciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 250, 40));

        jTabbedPane1.addTab("1", JpnMiplan);

        jPanel17.setBackground(new java.awt.Color(204, 204, 204));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Mis datos");
        jPanel17.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));
        jPanel17.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 170, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Numero Telefono");
        jPanel17.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        cbTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", " " }));
        jPanel17.add(cbTipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));
        jPanel17.add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 110, -1));
        jPanel17.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 150, -1));
        jPanel17.add(txPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 160, 20));

        btnActualizarInfo.setText("Actualizar mis datos");
        btnActualizarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarInfoActionPerformed(evt);
            }
        });
        jPanel17.add(btnActualizarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 160, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Nombres");
        jPanel17.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Apellidos");
        jPanel17.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("Documento");
        jPanel17.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Contraseña");
        jPanel17.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Correo Electronico");
        jPanel17.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Dirección");
        jPanel17.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));
        jPanel17.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 150, -1));
        jPanel17.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 150, -1));
        jPanel17.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 170, -1));

        javax.swing.GroupLayout JpnMisDatosLayout = new javax.swing.GroupLayout(JpnMisDatos);
        JpnMisDatos.setLayout(JpnMisDatosLayout);
        JpnMisDatosLayout.setHorizontalGroup(
            JpnMisDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnMisDatosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JpnMisDatosLayout.setVerticalGroup(
            JpnMisDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnMisDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("2", JpnMisDatos);

        jpnSoporte.setBackground(new java.awt.Color(204, 204, 204));
        jpnSoporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Soporte");
        jpnSoporte.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Asunto:");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Descripcion del problema:");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        btnEnviarSoporte.setBackground(new java.awt.Color(102, 102, 102));
        btnEnviarSoporte.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarSoporte.setText("Enviar");
        btnEnviarSoporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarSoporteActionPerformed(evt);
            }
        });
        jPanel7.add(btnEnviarSoporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 60, -1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(null);
        jScrollPane2.setViewportView(txtDescripcion);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 600, 100));
        jPanel7.add(txtAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 600, -1));

        jpnSoporte.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 650, 300));

        jTabbedPane1.addTab("3", jpnSoporte);

        JpnDetalles.setBackground(new java.awt.Color(204, 204, 204));
        JpnDetalles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Detalles de mi plan");
        JpnDetalles.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Metodo de pago:");
        JpnDetalles.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("ID del plan:");
        JpnDetalles.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Fecha de activacion: ");
        JpnDetalles.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Descripcion del plan:");
        JpnDetalles.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Fecha de vencimiento:");
        JpnDetalles.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("Estado del plan:");
        JpnDetalles.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Costo mensual:");
        JpnDetalles.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        JpnDetalles.add(txtnombrePlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 160, -1));
        JpnDetalles.add(txtmetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 160, -1));
        JpnDetalles.add(txtvalorMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 160, -1));
        JpnDetalles.add(txtfechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 160, -1));
        JpnDetalles.add(txtfechaActivacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 160, -1));
        JpnDetalles.add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 160, -1));
        JpnDetalles.add(txtDescripcionPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 160, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Nombre del plan:");
        JpnDetalles.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));
        JpnDetalles.add(txtIdPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 160, -1));

        jTabbedPane1.addTab("4", JpnDetalles);

        JpnFacturacion.setBackground(new java.awt.Color(204, 204, 204));
        JpnFacturacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Facturacion");
        JpnFacturacion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jTabbedPane1.addTab("5", JpnFacturacion);

        JpnCambiarPlan.setBackground(new java.awt.Color(204, 204, 204));
        JpnCambiarPlan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Cambiar plan");
        JpnCambiarPlan.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jTabbedPane1.addTab("6", JpnCambiarPlan);

        JpnActualizarDatos.setBackground(new java.awt.Color(204, 204, 204));
        JpnActualizarDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("Nueva contraseña");
        jPanel6.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 120, -1));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 0));
        jLabel51.setText("Nombres");
        jPanel6.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, -1));

        txtActualizarNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActualizarNombresActionPerformed(evt);
            }
        });
        jPanel6.add(txtActualizarNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 180, -1));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 0, 0));
        jLabel52.setText("Apellidos");
        jPanel6.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, -1));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 0, 0));
        jLabel53.setText("No Documento");
        jPanel6.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 140, -1));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 0, 0));
        jLabel54.setText("Correo Electronico");
        jPanel6.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 140, -1));
        jPanel6.add(txtActApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 180, -1));
        jPanel6.add(txtActNoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 180, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 0, 0));
        jLabel55.setText("Direccion");
        jPanel6.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 140, -1));
        jPanel6.add(txtActDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 180, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Actualizar mis datos");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 0, 0));
        jLabel56.setText("Telefono");
        jPanel6.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, -1));
        jPanel6.add(txtActTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 180, -1));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 0, 0));
        jLabel57.setText("Contraseña actual");
        jPanel6.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 120, -1));
        jPanel6.add(txtActCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 180, -1));

        btnGuardar.setText("Guardar ");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel6.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 90, -1));

        btnCancelar.setText("Cancelar");
        jPanel6.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 90, -1));
        jPanel6.add(txtNuevaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 170, -1));
        jPanel6.add(txtContraseñaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 140, -1));

        JpnActualizarDatos.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 370));

        jTabbedPane1.addTab("7", JpnActualizarDatos);

        JpnActualizarMetodoPago.setBackground(new java.awt.Color(204, 204, 204));
        JpnActualizarMetodoPago.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Actualizar metodo de pago");
        JpnActualizarMetodoPago.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jTabbedPane1.addTab("8", JpnActualizarMetodoPago);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("Actualizar mi plan");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jTabbedPane1.addTab("9", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("10", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 780, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInicioMouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jPanelInicioMouseClicked

    private void jPanelInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInicioMouseEntered
        jPanelInicio.setBackground(new Color(30, 58, 138));
    }//GEN-LAST:event_jPanelInicioMouseEntered

    private void jPanelInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInicioMouseExited
        jPanelInicio.setBackground(new Color(59, 130, 246));
    }//GEN-LAST:event_jPanelInicioMouseExited

    private void jPanelMiplanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMiplanMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jPanelMiplanMouseClicked

    private void jPanelMiplanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMiplanMouseEntered
        jPanelMiplan.setBackground(new Color(30, 58, 138));
    }//GEN-LAST:event_jPanelMiplanMouseEntered

    private void jPanelMiplanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMiplanMouseExited
        jPanelMiplan.setBackground(new Color(59, 130, 246));
    }//GEN-LAST:event_jPanelMiplanMouseExited

    private void jPanelMisDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMisDatosMouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jPanelMisDatosMouseClicked

    private void jPanelMisDatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMisDatosMouseEntered
        jPanelMisDatos.setBackground(new Color(30, 58, 138));
    }//GEN-LAST:event_jPanelMisDatosMouseEntered

    private void jPanelMisDatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMisDatosMouseExited
        jPanelMisDatos.setBackground(new Color(59, 130, 246));
    }//GEN-LAST:event_jPanelMisDatosMouseExited

    private void JpnSoporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpnSoporteMouseClicked
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_JpnSoporteMouseClicked

    private void JpnSoporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpnSoporteMouseEntered
        JpnSoporte.setBackground(new Color(30, 58, 138));
    }//GEN-LAST:event_JpnSoporteMouseEntered

    private void JpnSoporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpnSoporteMouseExited
        JpnSoporte.setBackground(new Color(59, 130, 246));
    }//GEN-LAST:event_JpnSoporteMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel27MouseClicked

    private void JpnCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpnCerrarSesionMouseEntered
        JpnCerrarSesion.setBackground(new Color (30, 58, 138));
    }//GEN-LAST:event_JpnCerrarSesionMouseEntered

    private void JpnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpnCerrarSesionMouseExited
        JpnCerrarSesion.setBackground(new Color (59, 130, 246));
    }//GEN-LAST:event_JpnCerrarSesionMouseExited

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombre= txtActualizarNombres.getText().trim();
        String apellidos= txtActApellidos.getText().trim();
        String telefono= txtActTelefono.getText().trim();
        String documento= txtActNoDocumento.getText().trim();
        String direccion= txtActDireccion.getText().trim();
        String correo= txtActCorreo.getText().trim();
        String contrasenaactual= new String (txtContraseñaActual.getPassword());
        String contrasenanueva = new String(txtNuevaContraseña.getPassword());

        if (nombre.isEmpty() || apellidos.isEmpty() || telefono.isEmpty() || documento.isEmpty() ||
            direccion.isEmpty() || correo.isEmpty() || contrasenaactual.isEmpty() ||  contrasenanueva.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.", "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
            JOptionPane.showMessageDialog(this, "El nombre solo debe contener letras");
            return;
        }

        if(!apellidos.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")){
            JOptionPane.showMessageDialog(this, "El apellido solo debe contener letras");
            return;
        }

        if(!telefono.matches("\\d{10}")){
            JOptionPane.showMessageDialog(this,"El numero de telefono debe tener exactamente 10 numeros");
            return;

        }

        if(!documento.matches("\\d{7,10}")){
            JOptionPane.showMessageDialog(this, "El numero del documento debe contener entre 7 y 10 digitos");
            return;
        }

        if(!correo.contains("@")|| !correo.contains(".")){
            JOptionPane.showMessageDialog(this, "Correo invalido");
            return;
        }

        if(contrasenaactual.equals(contrasenanueva)){
            JOptionPane.showMessageDialog(this, "La nueva contraseña debe ser distinta");
            return;
        }

        if(contrasenanueva.length() < 8){
            JOptionPane.showMessageDialog(this, "La contrasena debe contener minimo 8 caracteres");
            return;

        }

        JOptionPane.showMessageDialog(this, "Datos actualizados correctamente");

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtActualizarNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActualizarNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActualizarNombresActionPerformed

    private void btnEnviarSoporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarSoporteActionPerformed
     String usuario = usuarioActual.getNombre(); // tu objeto Usuario
    String asunto = txtAsunto.getText();
    String mensaje = txtDescripcion.getText();

    if(asunto.isEmpty() || mensaje.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Completa todos los campos");
        return;
    }

    String mensajeCompleto = "Usuario: " + usuario + "\n\n" + mensaje;

    boolean enviado = correoSoporte.enviarCorreo("mauriciomaldonadomercado@gmail.com", asunto, mensajeCompleto);

    if(enviado) {
        JOptionPane.showMessageDialog(this, "Mensaje enviado correctamente");
        txtAsunto.setText("");
        txtDescripcion.setText("");
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo enviar el mensaje");
    }
    }//GEN-LAST:event_btnEnviarSoporteActionPerformed

    private void btnActualizarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarInfoActionPerformed
        jTabbedPane1.setSelectedIndex(7);
       
    }//GEN-LAST:event_btnActualizarInfoActionPerformed

    private void btnActualizarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPlanActionPerformed
       jTabbedPane1.setSelectedIndex(10);
    }//GEN-LAST:event_btnActualizarPlanActionPerformed

    private void btnDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesActionPerformed
        jTabbedPane1.setSelectedIndex(4);
        
          if (crud_planes.contadorPlanes > 0) {
        model.plan planActual = crud_planes.planes[0]; 

        txtIdPlan.setText(String.valueOf(planActual.getIdPlan()));
        txtnombrePlan.setText(planActual.getNombrePlan());
        txtvalorMensual.setText(String.valueOf(planActual.getValorMensual()));
        txtDescripcionPlan.setText(planActual.getDescripcionPlan());
        txtfechaVencimiento.setText(planActual.getFechaVencimiento());
        txtfechaActivacion.setText(planActual.getFechaActivacion());
        txtestado.setText(planActual.getEstado()); 
        txtmetodoPago.setText(planActual.getMetodoPago());
        
        txtIdPlan.setEditable(false);
        txtnombrePlan.setEditable(false);
        txtvalorMensual.setEditable(false);
        txtDescripcionPlan.setEditable(false);
        txtfechaVencimiento.setEditable(false);
        txtfechaActivacion.setEditable(false);
        txtestado.setEditable(false);
        txtmetodoPago.setEditable(false);
    } else {
        JOptionPane.showMessageDialog(this, "El usuario no tiene un plan asignado.");
    }
        
    }//GEN-LAST:event_btnDetallesActionPerformed

    private void btnOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionesActionPerformed
        jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_btnOpcionesActionPerformed

    private void btnFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionActionPerformed
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_btnFacturacionActionPerformed

    private void btnOpciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpciones1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpciones1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
        // objeto Usuario
        Usuario usuario = new Usuario("Mauricio","Maldonado","3101234567","correo@gmail.com","123456","CC", "Calle 10", "clave123 ");
        plan PlanActual = new plan (Crud_Planes.contadorId++, "Premium", "Acceso completo a todos los servicios","2025-11-02","2025-12-01","Activo",50000,"Tarjeta de crédito");
        new usuario(usuario).setVisible(true);
        
    }
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpnActualizarDatos;
    private javax.swing.JPanel JpnActualizarMetodoPago;
    private javax.swing.JPanel JpnBienvenida;
    private javax.swing.JPanel JpnCambiarPlan;
    private javax.swing.JPanel JpnCerrarSesion;
    private javax.swing.JPanel JpnDetalles;
    private javax.swing.JPanel JpnFacturacion;
    private javax.swing.JPanel JpnMenu;
    private javax.swing.JPanel JpnMiplan;
    private javax.swing.JPanel JpnMisDatos;
    private javax.swing.JPanel JpnPng;
    private javax.swing.JPanel JpnSoporte;
    private javax.swing.JButton btnActualizarInfo;
    private javax.swing.JButton btnActualizarPlan;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDetalles;
    private javax.swing.JButton btnEnviarSoporte;
    private javax.swing.JButton btnFacturacion;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnOpciones;
    private javax.swing.JButton btnOpciones1;
    private javax.swing.JComboBox<String> cbTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JPanel jPanelMiplan;
    private javax.swing.JPanel jPanelMisDatos;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jpnSoporte;
    private javax.swing.JPasswordField txPassword;
    private javax.swing.JTextField txtActApellidos;
    private javax.swing.JTextField txtActCorreo;
    private javax.swing.JTextField txtActDireccion;
    private javax.swing.JTextField txtActNoDocumento;
    private javax.swing.JTextField txtActTelefono;
    private javax.swing.JTextField txtActualizarNombres;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtAsunto;
    private javax.swing.JPasswordField txtContraseñaActual;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtDescripcionPlan;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdPlan;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JPasswordField txtNuevaContraseña;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtfechaActivacion;
    private javax.swing.JTextField txtfechaVencimiento;
    private javax.swing.JTextField txtmetodoPago;
    private javax.swing.JTextField txtnombrePlan;
    private javax.swing.JTextField txtvalorMensual;
    // End of variables declaration//GEN-END:variables

}
